name: PA System
version: "1.0.7"
slug: pa_system
panel_icon: mdi:bullhorn
panel_title: PA System
panel_admin: false
ingress: true
ingress_stream: true
description: "Live Mic PA System using HA Media Players"
url: "https://github.com/LOOHP/home-assistant-apps"
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
startup: services
boot: auto
init: false
host_network: true
map:
  - type: homeassistant_config
    read_only: false
options:
  home_assistant_ip: "192.168.1.3"
  ha_token: ""
  log_level: "info"
  targets_json: |
    [
      {
        "id": "living_room",
        "name": "Living Room",
        "entity_id": "media_player.audio_living_room",
        "kind": "speaker"
      },
      {
        "id": "audio_bedroom",
        "name": "Audio Bedroom",
        "entity_id": "media_player.audio_bedroom",
        "kind": "speaker"
      }
    ]
schema:
  home_assistant_ip: str
  ha_token: password
  log_level: list(trace|debug|info|warning|error|critical)
  targets_json: str
